# For parameters details, see this commented example: https://github.com/gustaveroussy/sopa/blob/main/workflow/config/example_commented.yaml
read:
  technology: toy_dataset

patchify:
  patch_width_pixel: 1200
  patch_overlap_pixel: 50
  patch_width_microns: 3000
  patch_overlap_microns: 40

segmentation:
  cellpose:
    diameter: 35
    channels: ["DAPI"]
    flow_threshold: 2
    cellprob_threshold: -6
    min_area: 2500

  comseg:
    min_area: 10

    config:
      dict_scale:
        x: 1
        y: 1
        z: 1
      mean_cell_diameter: 15
      max_cell_radius: 25
      allow_disconnected_polygon: false
      alpha: 0.5
      min_rna_per_cell: 5
      norm_vector: false # [optional] requires exeternal R package '"sctransform"' "feather" and "arrow" to be installed, otherwise set to false

aggregate:
  aggregate_channels: true

annotation:
  method: fluorescence
  args:
    marker_cell_dict:
      CK: Tumoral cell
      CD3: T cell
      CD20: B cell

explorer:
  ram_threshold_gb: 4
  pixel_size: 1
