# For parameters details, see this commented example: https://github.com/gustaveroussy/sopa/blob/master/workflow/config/example_commented.yaml
read:
  technology: uniform
  kwargs:
    transcript_cell_id_as_merscope: true

patchify:
  patch_width_pixel: 1200
  patch_overlap_pixel: 50
  patch_width_microns: 400
  patch_overlap_microns: 20

segmentation:
  baysor:
    min_area: 10
    cell_key: "cell_id"
    unassigned_value: -1

    config:
      data:
        force_2d: true
        min_molecules_per_cell: 10
        x: "x"
        y: "y"
        z: "z"
        gene: "genes"
        min_molecules_per_gene: 0
        min_molecules_per_segment: 3
        confidence_nn_id: 6

      segmentation:
        scale: 3 # typical cell radius
        scale_std: "25%" # cell radius standard deviation
        prior_segmentation_confidence: 0
        estimate_scale_from_centers: false
        n_clusters: 4
        iters: 500
        n_cells_init: 0
        nuclei_genes: ""
        cyto_genes: ""

aggregate:
  average_intensities: true
  min_transcripts: 5 # [optional] cells whose transcript count is below that this threshold are filtered

annotation:
  method: fluorescence
  args:
    marker_cell_dict:
      CK: Tumoral cell
      CD3: T cell
      CD20: B cell

explorer:
  gene_column: "genes"
  ram_threshold_gb: 4
  pixel_size: 0.1

executables:
  baysor: ~/.julia/bin/baysor
