read:
  technology: qptiff
  kwargs:
    channels_renaming:
      DAPI MSI: DAPI
      Opal 780 MSI: CK
      Opal 480 MSI: CD3
      Cy5 MSI: CD31
      FITC: FAP
      Cy3: CD68
      Texas Red: CD20

patchify:
  patch_width_pixel: 3000
  patch_overlap_pixel: 40

segmentation:
  cellpose:
    diameter: 15
    channels: ["DAPI"]
    flow_threshold: 2
    cellprob_threshold: -6
    min_area: 75

aggregate:
  average_intensities: true
  min_intensity_ratio: 0.1

annotation:
  method: fluorescence
  args:
    marker_cell_dict:
      CK: Tumoral cell
      CD3: T cell
      CD31: Endothelial
      FAP: Fibroblast
      CD68: Macrophage
      CD20: B cell

explorer:
  ram_threshold_gb: 8
