# Run proseg segmentation on Visium HD data using the 10X Genomics as prior segmentation.

# For parameters details, see this commented example: https://github.com/gustaveroussy/sopa/blob/main/workflow/config/example_commented.yaml
read:
  technology: visium_hd

patchify:
  patch_width_microns: -1

segmentation:
  proseg:
    prior_shapes_key: auto

aggregate:
  aggregate_channels: true
  min_transcripts: 10 # [optional] cells whose transcript count is below that this threshold are filtered

explorer:
  ram_threshold_gb: 4
