# Config file to run proseg segmentation on 10X Visium HD data from their website (with their prior segmentation)
# NB: this only works when a full-resolution images is present

# For parameters details, see this commented example: https://github.com/gustaveroussy/sopa/blob/main/workflow/config/example_commented.yaml
read:
  technology: visium_hd
  kwargs:
    dataset_id: "" # Important: you need this line if you load data from the 10X genomics website

patchify:
  patch_width_microns: -1

segmentation:
  proseg:
    prior_shapes_key: auto

aggregate:
  aggregate_channels: false
  min_transcripts: 10 # [optional] cells whose transcript count is below that this threshold are filtered

scanpy_preprocess:
  check_counts: false

explorer:
  ram_threshold_gb: 4
