read:
  technology: visium_hd
  kwargs:
    imread_kwargs:
      page: 0

patchify:
  patch_width_pixel: 2000
  patch_overlap_pixel: 50

segmentation:
  stardist:
    min_area: 30

aggregate:
  aggregate_channels: true
  min_transcripts: 10 # [optional] cells whose transcript count is below that this threshold are filtered

scanpy_preprocess:
  resolution: 1
  check_counts: false

explorer:
  ram_threshold_gb: 4
